### ISSUE TITLE
Error for Spigot (and forks) 1.19.4 on start-up

### ISSUE THREAD

**Issue by AggerTV** [BlackDemonZyT/BotSentry#100]
Hello, I noticed this error in the console when i startup the server
https://pastebin.com/MGiDX6MW

Server info:
Pufferfish+ version git-PufferfishPlus-48 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 88f6236 on HEAD)

Botsentry info:
BotSentry version 9.5.2-THANATOS

**Comment by Laurenshup** [comment]
A fix will be released before this weekend, so today or tomorrow!

**Comment by Laurenshup** [comment]
The error has been found in the code, and is fixed. Due to time contraints, the actual release will be Saturday (tomorrow).

**Comment by Laurenshup** [comment]
The update has been built and sent to @BlackDemonZyT to publish on the marketplaces.

**Comment by Laurenshup** [comment]
Released
