### ISSUE TITLE
Even more (probably huge) optimization to the PreLoginEvent

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#11]
Well, i'm probably wrong but i don't think i am, the check that we currently have in the PreLoginEvent, that checks how many nicknames are playing with your IP when you try to join, ii think that we are currently requesting the "bungee api?" to return us an Array with the  online users and their IPs, and then we count the amount of nicknames that are using that IP before joining.

Well, i think i have an idea that can optimize the plugin a lot, instead of requesting a list of players->ips to the bungee every time that someone tries to join, to check his amount of nicknames playing with his IP, we could make that the plugin asks the bungeecord that list every second and stores it in an Array, and, when a player join we directly count the amount of nicknames per his IP are playing, with this pre-made array that is updated every 1 second. This way if theres a +1000 bots per second attack going on, it won't to do like other plugins, asking the list of online playersname->ip for every join, insead it will do that every second, and for every join it will just  make a contains in that auto-updated List.

**Comment by Laurenshup** [comment]
Pretty sure we are not doing this. I will check it next time when I am developing.

**Comment by Laurenshup** [comment]
Okay I have investigated into this problem.

First of all, we are not checking all online player users on PreLoginEvent.
We are checking it on PostLoginEvent, only after all other checks.

Secondly, we are already saving everything in an array with an object. It already saved all online users in an object.
