### ISSUE TITLE
Request for Folia Support

### ISSUE THREAD

**Issue by CormacZ** [BlackDemonZyT/BotSentry#110]
https://papermc.io/software/folia

**Comment by Laurenshup** [comment]
I just checked, since this is a fork of Paper, does it not already work?

**Comment by CormacZ** [comment]
> I just checked, since this is a fork of Paper, does it not already work?

I think I remember something has to do with plugin.yml to make it work on Folia. I forgot what to add but yeh. something in that yml,

**Comment by Laurenshup** [comment]
It is: `folia-supported: true`, I will have to check whether BotSentry seems to function normally on Folia or not. If it does, I will allow the plugin to be used on Folia, since Folia is not in its stable release phase, I cannot guarantee support for it, as it might break at any time.

**Comment by Laurenshup** [comment]
I have coded this into the plugin. I cannot grant that it works on any Folia version, as it is still completely in development phase.
