### ISSUE TITLE
Kick : Lost connection: Received chat packet with missing or invalid signature

### ISSUE THREAD

**Issue by Draghonir** [BlackDemonZyT/BotSentry#112]
Hello, I've just discovered a rather troublesome bug in BotSentry at version minecraft 1.20.2 and I'd like to explain the steps I took to confirm that it was indeed the culprit. When players connect and send a message in the chat, the message doesn't get sent to the server, and the players get kicked with the following message: "Lost connection: Received chat packet with missing or invalid signature." There were no other errors in the console. So, what I did was migrate all the plugins to a test server and removed them one by one to identify the responsible plugin. I found that it was BotSentry because when I reinstalled all the plugins except for BotSentry, everything worked fine. When I added BotSentry back, the same issue of the "kick lost connection: Received chat packet with missing or invalid signature" occurred. If necessary, I can provide video evidence to demonstrate this issue. 

https://youtu.be/K60S-NZhLSI (No botsentry, no kick)

https://youtu.be/EwX7BoLM_VM (With botsentry, kick Lost connection: Received chat packet with missing or invalid signature)

The log capture is after the second video youtube 

<img width="970" alt="gf" src="https://github.com/BlackDemonZyT/BotSentry/assets/107469643/b012262d-3070-4ca2-a38e-e863069e414a">

**Comment by Laurenshup** [comment]
Hi, can you confirm you have detection.amazon.enabled set to true? What happens if you set it to false?

**Comment by Draghonir** [comment]
Hi,

yes my detection.amazon was set to true, after set to false bug was fix

what difference does it make to have this set to false Should I expect a drop in efficiency?

**Comment by Laurenshup** [comment]
Amazon checks whether players send some specific packets. While players haven't send it yet, any chat messages are blocked. Blocking chat messages is not allowed anymore on the proxy since the new encryption of chat messages in Minecraft.

The plugin will work the same, there is no drop in efficiency.

**Comment by Draghonir** [comment]
Alright, do you have plans in a future update to set it to 'false' by default to avoid this issue for players?"

**Comment by Laurenshup** [comment]
Hi @Draghonir, the setting for `detection.amazon.enabled` is already set to false now. We can change it remotely, which I have done one month ago. Therefore, when building a new config.yml, it should use the new setting.

**Comment by Laurenshup** [comment]
I will also include the information that the setting is not compatible with newer versions in the config.yml. It might also be an idea to include that this should mainly be used for the highest protection, but that it will most likely kick real players as well.

**Comment by smscentras** [comment]
All here have problem with detection.amazon when set to true
I have lost all my players when your plugin kicked ALL online players.

**Comment by Laurenshup** [comment]
I have also heard people who have it working. But as said above. Most special clients do not send the packets correctly, which kicks them. But I will look into removing it.

**Comment by smscentras** [comment]
I think third party plugins are to blame here. Like ViaVersion or ProtocolLib..
Even bedrock clients were kicked out.

**Comment by Laurenshup** [comment]
Since amazon is disabled by default, and the message attached to it has changed in the newest version. Amazon has been completely removed from Spigot platforms, I believe this is done.
