### ISSUE TITLE
Bug: MySQL Error Code 0 - Velocity

### ISSUE THREAD

**Issue by Greazi-Times** [BlackDemonZyT/BotSentry#113]
**Server Info (please complete the following information):**
 - Server Type: Velocity
 - Server Version: Velocity 3.2.0-SNAPSHOT (git-f884e049-b275)
 - Java Version 17
 - Online-Mode: True
 - BungeeCord: True

**Plugin Info (please complete the following information):**
 - Version: 9.5.3-THANATOS
 - MySQL: Yes

**Describe the bug**
When starting up the server it gives a `MySQL Error Code 0` error that repeats every x amount of time.
Because of this it doesn't get the information from the database.

**To Reproduce**
1. Configure a database
2. Reload/Restart the proxy
3. Wait for BotSentry loading message

**Expected behavior**
Connect to the database

**Comment by Greazi-Times** [comment]
![image](https://github.com/BlackDemonZyT/BotSentry/assets/69437555/7c38714c-29db-49f2-9c45-fb3feccc8587)
As shown in the image it says that a class is deprecated and a new class needs to be used.

**Comment by gamer50082** [comment]
```txt
[00:39:02 ERROR]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```

**Comment by Laurenshup** [comment]
This is now fixed within the code, which will be uploaded in the next version.
