### ISSUE TITLE
Error when disabling the plugin

### ISSUE THREAD

**Issue by ViktorAggerholm** [BlackDemonZyT/BotSentry#114]
Server version: git-PufferfishPlus-22 (MC: 1.20.2)
Botsentry version 9.5.3-THANATOS

When restarting my server I noticed this error always shows in the console
https://pastebin.com/Fq6rdyBk

**Comment by smscentras** [comment]
Server version 1.20.2(Paper)

**Comment by Laurenshup** [comment]
This is because we use PacketListenerAPI, it seems like they have some errors causing this. I could update to the newest version, but I am not sure if this fixes it.

**Comment by Laurenshup** [comment]
This has been fixed within the code.
