### ISSUE TITLE
BotSentry's console filter overrides existing filter(s)

### ISSUE THREAD

**Issue by Remigio07** [BlackDemonZyT/BotSentry#115]
Platform: Waterfall 1.20 #543, Java 17
Plugins: BotSentry, a custom plugin created to test the issue

My plugin takes some time to perform the ProxyPingEvent to customize the proxy's MoTD and when events take more than 50 ms (or something like that) a warning message is printed:

![image](https://github.com/BlackDemonZyT/BotSentry/assets/31587616/a5bd7fd0-750c-4c62-ba3e-6488624f9fc0)

To prevent this, I have set the BungeeCord console's logger's filter so that it filters out that warning message:

```java
java.util.logging.Logger logger = ProxyServer.getInstance().getLogger();
Filter oldFilter = logger.getFilter();

logger.setFilter(new Filter() {
	
	@Override
	public boolean isLoggable(LogRecord record) { // method used to check whether to filter out the message or not
		return (oldFilter == null || oldFilter.isLoggable(record)) && !Utils.numericPlaceholders(record.getMessage(), record.getParameters() == null ? new Object[0] : record.getParameters()).contains("vent ProxyPingEvent(connection=");
	}

});
```

The `Utils.numericPlaceholders(LogRecord)` method is just a placeholder replacer that replaces `{0}`, `{1}`, etc. with the values specified:

```java
/**
* Replaces numeric placeholders in a string with the given arguments:
 * 	<ul>
 * 		<li><code>{0}</code> will be replaced with <code>args[0]</code></li>
 * 		<li><code>{1}</code> will be replaced with <code>args[1]</code></li>
 * 		<li><code>{7}</code> will be replaced with <code>args[7]</code></li>
 * 	</ul>
 * 
 * ...and so on.
 * 
 * @param string String containing placeholders
 * @param args Optional arguments
 * @return String with placeholders translated
 */
public static String numericPlaceholders(String string, Object... args) {
	for (int i = 0; i < args.length; i++)
		if (string.contains("{" + i + "}"))
			string = string.replace("{" + String.valueOf(i) + "}", String.valueOf(args[i]));
	return string;
}
```

If my plugin loads after BotSentry, the filter is set correctly and the warning message is not printed, but if it loads after BS, the antibot replaces my previously filter (and potentially other plugins', too) with its own one.
I have found a temporary workaround that sets the filter 5 seconds after the plugin's startup to ensure its correct functioning, but obviously other plugins may need it as well and their filter will be replaced.

What I am asking is that BotSentry uses a method similar to the one in the first snippet of code which will consider any previously set filters when processing the messages to filter out.

**Comment by Laurenshup** [comment]
This has been looked at in the code. It seemed like this was only the case for BungeeCord, as it uses a special logger. This has been developed in code and will be published in the next version: It will always do BotSentry's filtering first, if BotSentry thinks the message should not be filtered it will forward it to a previously set filter.
