### ISSUE TITLE
Add MySQL SSL support

### ISSUE THREAD

**Issue by gamer50082** [BlackDemonZyT/BotSentry#117]
using JDBC

**Comment by gamer50082** [comment]
HikariCP is an option

**Comment by Laurenshup** [comment]
Already using JDBC, SSL has been enabled within the code. Still need to test whether it works now. HikariCP is not being used.

**Comment by gamer50082** [comment]
Make it toggleable

**Comment by Laurenshup** [comment]
It will first try to establish a connection using SSL. If Java cannot build up a working connection, it will check whether the server also allows non-SSL connections, and use that.

**Comment by coolxitech** [comment]
> It will first try to establish a connection using SSL. If Java cannot build up a working connection, it will check whether the server also allows non-SSL connections, and use that.

Perhaps automatic reconnection to non SSL MySQL did not work？
