### ISSUE TITLE
Add support for importing multiple ips to whitelist or blacklist

### ISSUE THREAD

**Issue by IncarnateWill** [BlackDemonZyT/BotSentry#119]
I have for example almost 3k ip s of proxies/vpns and i want to add them to the blacklist and i have to do it one by one

**Comment by Laurenshup** [comment]
It is technically possible to put them into the blacklist file, but I understand that it would require some reformatting. How exactly would you wish to let this work? Import from file, special command, ip ranges?

**Comment by Laurenshup** [comment]
This has been added inside of the code, to be released in the next version.
IPs can now be added like this: 1.2.3.4,1.2.3.5,1.2.3.6/31. Commas will split IPs. Adding / will use the IP range.
