### ISSUE TITLE
Memory-leak preventing (I think this is 1 of the factor of ram usage)

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#12]
The logs, night-brain-storming made me arrive to the conclusion, that, the Blacklist in ram cannot cause a memory leak because it contains unique IPs and no one have 99999999 proxies to load up the whole ram. But, what about logs?

During an attack, aren't the BotSentry logs constantly growing in ram? You can leave a 24/7 attack and logs will keep growing up all time.

In my opinion, a good optimization on logs would be saving them every X seconds, and cleaning them up from the ram, like, partially saving them into the disk and cleaning up ram every X seconds.

**Comment by Laurenshup** [comment]
True. This is smart.

**Comment by BlackDemonZyT** [comment]
Well just though that better and that would also lead to a infinite disk usage with an attack of a lot of hours xD

Can't think of a real solution to this, probably just setting logs: to false by default and asking to enable them just for debug purposes.

**Comment by Laurenshup** [comment]
As you said. I can clear RAM and save into files, after X seconds or after X objects.

**Comment by Laurenshup** [comment]
Has been added in the upcoming version. It saves into the file system when there are 1000 logs (around 1 MB). This value will be configurable in a later version.
