### ISSUE TITLE
BotSentry on Velocity doesn't work with LimboAUTH plugin (Which uses limboAPI plugin aswell)

### ISSUE THREAD

**Issue by xFocuSed** [BlackDemonZyT/BotSentry#124]
No logs displayed, no errors.

Latest Velocity and PLUGINS!

Blacklist doesn't function while plugin LimboAuth is with limboapi (which is needed cuz as dependency)
also it doesn't check IP.
Scan works amazing which check if it is proxy (detect it)
No first join message when enabled

**Comment by Laurenshup** [comment]
Hi, did you already fix this, as you already close it?

**Comment by xFocuSed** [comment]
> Hi, did you already fix this, as you already close it?

No I didn't, It was closed because my account went down for a day due to github issues with my account 
Issue still exists, no possible fixes found

**Comment by pVICTORIAAAA** [comment]
Okay imma start new issue then.

**Comment by pVICTORIAAAA** [comment]
https://github.com/BlackDemonZyT/BotSentry/issues/125

**Comment by Laurenshup** [comment]
Please, never make new issues, just reopen it next time.
