### ISSUE TITLE
New auto-save configurable, to prevent data loss on server crash

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#13]
Basically a guy told me this suggestion and i think its a really good idea

Copy pasting the Auto-Purger things, but changing them for Auto-Save.

Auto Save blacklist into the file every X time, or after attack , or when X blacklist amount is reached...
same for whitelist
same for logs.

So if the server crashes or gets hard-closed, the logs, blacklisted ips in that session and whitelisted ips in that sesions wont get lost.

**Comment by Laurenshup** [comment]
Somehow, forgot to close this. This is already introduced in 9.5.
