### ISSUE TITLE
Lockdown time going negative

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#17]
https://prnt.sc/11z9fxi

**Comment by Laurenshup** [comment]
Need more information. Did the attack really take 53130 seconds already?

**Comment by BlackDemonZyT** [comment]
> Need more information. Did the attack really take 53130 seconds already?

Unfortunately i don't know, i don't remember the guy that reported this to ask him, but it don't think the attack took 14 hours xD

**Comment by Laurenshup** [comment]
I cannot reproduce this issue. There is no real way of this happening on the newest version.

**Comment by Laurenshup** [comment]
I saw you said this is from the latest version in WhatsApp. Can you really confirm that?

**Comment by Laurenshup** [comment]
@BlackDemonZyT As you do not know any more details, I sadly cannot finish this.

**Comment by BlackDemonZyT** [comment]
If a next user reports this, we will be able to reproduce it better.

**Comment by Laurenshup** [comment]
Will close this for now. If more information is available, we can open it again.
