### ISSUE TITLE
MCMarket Jar not changing the Market ID in the variable

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#19]
There are a lot of mcmarket customers with the mcmarket_id %%__USER__%%, but they purchased the plugin.

**Comment by Laurenshup** [comment]
It displays as %%USER%%? This only happens on the newest version? Do you
have any screenshots or a JAR?

Op ma 26 apr. 2021 00:06 schreef BlackDemonZyT ***@***.***>:

**Comment by BlackDemonZyT** [comment]
Sent the .jar in whatsapp to prevent leakage. I will say when i know if it only happens on the latest version.

And yes, verified mcmarket customer, he downloaded the .jar, introduced it on the server, i checked his IP and he has %%__USER__%% on his .jar downloaded from mcmarket, version 9.0.

**Comment by Laurenshup** [comment]
Ah. GitHub adds markdown. It has the underscores in the JAR. Looks like McMarket is not applying IDs

**Comment by BlackDemonZyT** [comment]
Confirmed this only happens on 9.0-THANATOS, in 8.8.1 it works perfectly.

**Comment by Laurenshup** [comment]
Very odd.
After doing some research: https://www.mc-market.org/threads/628591/
It looks like this bug is because of MCMarket. Reuploading the version should fix it, if it does not, then it is good to make a ticket.
