### ISSUE TITLE
/ Bs does not work in the latest version of BotSentry. (Paper 1.8.8)

### ISSUE THREAD

**Issue by ST3RmY** [BlackDemonZyT/BotSentry#20]
When I run any BotSentry command it doesn't work and I get this error:

https://pastebin.com/F8z3AvtR

**Comment by ST3RmY** [comment]
I'm Using latest of Paper Spigot 1.8.8

**Comment by Laurenshup** [comment]
This issue seems to have some errors with the new message system.
This is also happening because of this: https://cdn.discordapp.com/attachments/620327952961241139/835195512855855184/2021-04-23_18-34-08.mp4

**Comment by Laurenshup** [comment]
Seems to be happening on Spigot 1.8.8 too.
I can assume it is happening for all forks of Spigot.

**Comment by ST3RmY** [comment]
how i fix this error?

**Comment by Laurenshup** [comment]
I have found a fix for this issue. I am currently testing it on all versions of Spigot (and some forks).
It will be added into the upcoming 9.0.1-THANATOS update. Which will come out sometime this or next week.

**Comment by Laurenshup** [comment]
Has been successfully tested and fixed.
