### ISSUE TITLE
List of IPs Dolly will not check for

### ISSUE THREAD

**Issue by Laurenshup** [BlackDemonZyT/BotSentry#25]
For example, if a local IP has to join with many accounts. It would be easier to just add that IP to a list and it will not check for Dolly for that IP.

**Comment by SottaByte98** [comment]
it would be awesome to be able to check and set the limit using permission aswell
like botsentry.connectenlimit.5
or botsentry.connectenlimit.bypass

**Comment by Laurenshup** [comment]
> it would be awesome to be able to check and set the limit using permission aswell
> like botsentry.connectenlimit.5
> or botsentry.connectenlimit.bypass

Sadly this is not an option as permissions are per player and not per IP basis.

**Comment by Laurenshup** [comment]
The list has been added in the upcoming version.
