### ISSUE TITLE
Fix new method called MOTD Attack

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#26]
Basically this attack makes the machine use more than 500 MBPS of outgoing network.

In case the attack is 100k pings per sec, the server sends 100k times the server-icon, in our tests, this happen like this.

Suggested fix: Check if in the last second there have been more than 200 serverlistpings, dont't  send the server-icon in the next second. This way, it will be detecting this MOTD attacks and until it has not finished, it will  not be sending the server-icon.

Code suggested by the user that reported the issue:
event.getResponse().setFavicon("");

**Comment by Laurenshup** [comment]
I have not used that code
> event.getResponse().setFavicon("");

I am setting it to null, so it sends even less data.
