### ISSUE TITLE
Console error with packetlistenerapi

### ISSUE THREAD

**Issue by sk1pdxdxdx** [BlackDemonZyT/BotSentry#30]
Console spam , still repeating an error 

https://pastebin.com/5kwmBELi

**Comment by BlackDemonZyT** [comment]
PD: Trying to install PacketListenerAPI does not fix it.

**Comment by sk1pdxdxdx** [comment]
solved.i did full of plugins update

**Comment by Laurenshup** [comment]
Okay, other plugin was conflicting.
