### ISSUE TITLE
Anti-VPN Feature

### ISSUE THREAD

**Issue by DeOpping** [BlackDemonZyT/BotSentry#32]
May be hard to implement and may be unneeded since there are many free anti-vpn plugins, however I feel like since this is like a security plugin and helps prevent bot attacks, I feel as like an anti-vpn would be a nice feature, and if you do add this perhaps add a way to allow certain UUIDs to bypass the anti-vpn!

**Comment by Laurenshup** [comment]
Sorry for the late response.

We (as in the developers) have already thought about this a lot. But because of the huge increase in traffic for our server, because it has to check all IPs, we are going to make this a premium option.  This is still being worked on.

**Comment by Laurenshup** [comment]
Guess what, after discussing more. We are aiming to make this a free update. Only if our servers will handle it fine of course.

Currently this has been fully developed, only testing left.

**Comment by Laurenshup** [comment]
Looks like this works perfectly on both backend and frontend. This has now been added into the upcoming version!
