### ISSUE TITLE
Can not run any commands / type in chat when BotSentry is installed on the server

### ISSUE THREAD

**Issue by rawora-rg** [BlackDemonZyT/BotSentry#33]
Hello,
 
players on the Minecraft server can not run any commands / type in chat while BotSentry is installed.

We are using Airplane 1.17, and the newest version of the plugin.

**Comment by Laurenshup** [comment]
Disabling detection.amazon.enabled (set to false) should fix it. Confirm this please.

**Comment by rawora-rg** [comment]
Perfect, fixed it. Thank you for helping :)
