### ISSUE TITLE
Little Suggestions

### ISSUE THREAD

**Issue by AloneX079** [BlackDemonZyT/BotSentry#45]
1. Show a cool Title ingame when Antibot of BotSentry gets triggered. 
For Eg: 
/title @a title [{"text":"Bot","color":"red","bold":true}, {"text":"Sentry","color":"gold","bold":true}]
/title @a subtitle [{"text":"has been ","color":"red"},{"text":"deployed ","color":"gold","bold":true}]
# Give it a try atleast :)

2. Add -configure permission to Administrators also, instead of "Server Owner only" of BotSentry Public Discord bot. Because server owners are sleeping and Admins have to set these things for them!

**Comment by Laurenshup** [comment]
Please make two different issues.
