### ISSUE TITLE
Attempted Command

### ISSUE THREAD

**Issue by Leahcimkrob** [BlackDemonZyT/BotSentry#49]
Hello BlackDemonZyT, is it possible that the admin message shows which command was attempted?

**Comment by Laurenshup** [comment]
What does this have to do with BotSentry?

**Comment by Leahcimkrob** [comment]
BlackDemonZyT had sent me this link in the Discord to open a ticket here. It's about the ABPS

**Comment by Laurenshup** [comment]
Oh, this is also about ABPS? I thought you were asking something else, here are you at the wrong place. Just DM BlackDemonZyT.
