### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by KasprTv** [BlackDemonZyT/BotSentry#50]
Since the latst antiproxy update I started to experience high CPU usages. 

We made a few tests with Laurens.

CPU without firewall:
![image](https://user-images.githubusercontent.com/71224156/138554550-ca2fa10e-d054-473d-8bfd-4ad65615cd61.png)

CPU with firewall:
![image](https://user-images.githubusercontent.com/71224156/138554573-00ece64e-8dab-4280-b8f3-0a5e8d0d092a.png)

CPU with firewall, AntiProxy and server is under attack:
![image](https://user-images.githubusercontent.com/71224156/138554626-406a719f-43ac-4f29-b9ba-d9d21f4824f1.png)

**Comment by Laurenshup** [comment]
This is probably fixed together with #66. For now I am closing this.
