### ISSUE TITLE
Always-on AntiVPN

### ISSUE THREAD

**Issue by meMarcoo** [BlackDemonZyT/BotSentry#52]
I would to suggest a permission to avoid the new always-on anti vpn. Some players may be using often vpn, and can be annoying for those players to be kicked from servers without possibility to ask a whitelist from this check.

**Comment by Laurenshup** [comment]
Okay, I am not fully following you. You can just disable the 24/7 AntiProxy in the config?

**Comment by Laurenshup** [comment]
Due to the lack of information, I cannot do anything with this. As I am guessing, this configuration setting is already in the config.yml.
