### ISSUE TITLE
Blacklisted IP Bypass

### ISSUE THREAD

**Issue by FriLave** [BlackDemonZyT/BotSentry#53]
When a player's ip is blacklisted and the player is kicked, if the player reconnects without validating the captcha on notbot.es, his connection will not be blocked and he will bypass the blacklist.

![image](https://user-images.githubusercontent.com/69471654/141365692-72fc3786-b457-45f0-81de-15b38d1e2b11.png)

**Comment by Laurenshup** [comment]
I cannot recreate this problem. Can you tell me when this happens? Because I just tried this using the commands.

**Comment by FriLave** [comment]
After switching to Velocity 3.1.1 and BotSentry 3.2-THANATOS, the bug is no longer present
