### ISSUE TITLE
AntiBot Mode/automatic whitelisting for given usernames

### ISSUE THREAD

**Issue by Skaian** [BlackDemonZyT/BotSentry#54]
It would be great to have a permission to settle for specific groups of people or names to insure they can enter your server or feel more secured, extremely helpful for laggy people and can be a perk for special people.

**Comment by Laurenshup** [comment]
I will not add the permission bypass for the following two reasons:

At login initialisation there is no data of the player available yet. Permissions cannot be retrieved.
Permissions are managed by other plugins, we try to keep everything sorted out so bots do not consume unnecessary data.

**Comment by Laurenshup** [comment]
I also see a few problems with the username whitelist:
* Checking of usernames is currently not being done. An IP is checked on the backend.
* I cannot tie an username to an IP when the player with that username is not online.
* I cannot combine all accounts together using the same IP, this is used for several detection methods.


What I am proposing:
A list of usernames, if someone joins with that username. That IP will be fully whitelisted (removed from blacklist, allowed through AntiBot Mode). This username will stay in the seperate list.

**Comment by Laurenshup** [comment]
The base system has been successfully coded. A server owner, can now add usernames to the usernames whitelist. These usernames keep being whitelisted even when they are blacklisted. The things left to do: `MySQL integration`.

**Comment by Laurenshup** [comment]
Currently, the development for this is done. Now there is only a lot of testing left!

**Comment by Skaian** [comment]
Thanks much for the hard work, best developers ever.

**Comment by Laurenshup** [comment]
Thank you 😄. Everything has been tested. It is fully compatible with `MySQL`, it will add an additional column to the database, in order to support the system. Also added the extra integration into the `API`. With this update, there is also a second IPs whitelist (we now refer to them as `not forced` and `forced`). Inside of the forced IPs whitelist, those IPs are never removed by any of the detection methods.

**Comment by Laurenshup** [comment]
This will be included in the upcoming version.
