### ISSUE TITLE
Null message when prefix is true

### ISSUE THREAD

**Issue by Espantonius** [BlackDemonZyT/BotSentry#58]
When i set the "prefix" option to "true", the prefixed text appears as "null" in multiple messages.

Images:
https://i.gyazo.com/a535a46ca16572640e1aabafd2f23e37.png

Here the config and messages that i have used: https://gist.github.com/Espantonius/0c9e56181c51e5fbefa4a1b7df1c0d76

**Comment by Laurenshup** [comment]
Has been successfully fixed in the upcoming update (release before 2022)/
