### ISSUE TITLE
Extra parameter to kick subcommand & /bs accounts

### ISSUE THREAD

**Issue by Ronal1999** [BlackDemonZyT/BotSentry#68]
Can you pls add the command /bs kick <player/all><server> and will kick all players with multi accounts connected, like with ''all'' it will kick all players from the server specified if not specified it will run into the whole server, and add the option on how many accounts will be left online when execute the command, like #LeaveConnected: 1 or whatever you want

**Comment by Laurenshup** [comment]
So, there is already the /bs kick <player:ip> command which kicks all players on the same IP.
Would it not be better to do /bs kick <player:ip> <leaveConnected>. This way players can define in the command how many IPs should be left connected.

**Comment by Laurenshup** [comment]
I see now what you mean.
I am proposing the following changes: `/bs kick <player:ip:multiAccounts> [leaveConnected]`
This will be functionality:
- `/bs kick <ip> [leaveConnected]` - This will kick all or all minus the amount of `[leaveConnected]` players using the same IP.
- `/bs kick <player>[leaveConnected]` - This will function the same as the above function, but it will use the given player's IP.
- `/bs kick multiAccounts [leaveConnected]` - This will kick all or all minus the amount of `[leaveConnected]` players that have multiple players on the same IP.

**Comment by Laurenshup** [comment]
After thinking more about it this will be better: `/bs kick <ip:multipleAccounts> <args>`
With:
- `/bs kick ip <ip:player> [leaveConnected]`
- `/bs kick multipleAccounts [leaveConnected]`

**Comment by Ronal1999** [comment]
I would like you guys to do it globally like kick all alts from all players connected in a specific server like I have 20 users in survival, and 5 of them have 1 account extra and playing with the total of 2 account for IP, so what I do instead of searching, IP per IP, 
I do /bs kickall <server>, it will kick all players with alts account connected that moment and the other one is
 /bs alts all <server> it will show player with alts connected in the moment if you have another one and is offline it wont be on the list just player with last online in that moment

**Comment by Laurenshup** [comment]
The kicking of alts has been added into the `/bs kick` command.
`/bs alts` is another command however, I can add it. I will call it `/bs multipleAccounts`.

**Comment by Laurenshup** [comment]
After having a second thought. I will call it `/bs accounts`. This will list all IPs.

**Comment by Laurenshup** [comment]
Fully developed and tested! Coming in the upcoming version!
