### ISSUE TITLE
Turn off consolefiltering when antibotmode is not enabled

### ISSUE THREAD

**Issue by Erlpil** [BlackDemonZyT/BotSentry#79]
We have other systems reading our log files and would love to be able to keep reading our log normally when the server is not under attack.

There is a setting for this, but this seems to be deprecated:
```
# Console filtering settings
consolefiltering:
  # Should the console be filtered when attack?
  enabled: true
```

Would love to have this setting work again so we can keep processing our proxylog data.

**Comment by Laurenshup** [comment]
This has been coded, and will be included in the next version!
