### ISSUE TITLE
Auto-save whitelist and blacklist at intervals

### ISSUE THREAD

**Issue by Erlpil** [BlackDemonZyT/BotSentry#80]
At it's current state the plugin does not save changes to whitelist and blacklist other than with a graceful shutdown of the proxy or reload of the plugin.
If you have a crash/ungraceful shutdown of your proxy/server all progress since last restart is lost. The proxy is not the component that is restarted the most often so the data loss could be a long period of time.

Would be great if these list were saved at some interval. I don't know if the best time is 5 mins, 15 mins, 1 hour, 24 hour, but anything is better than nothing.

I hope this feature will make it into the plugin at some point. Thanks!

**Comment by Laurenshup** [comment]
I agree, this feature is quite welcome in BotSentry.

**Comment by Laurenshup** [comment]
This has been coded, and will be there in the next version!
