### ISSUE TITLE
Disconnect message of join

### ISSUE THREAD

**Issue by SkyDude0** [BlackDemonZyT/BotSentry#84]
Every time a player enters the server for the first time after restarting the proxy they receive a disconnect message.

This bug only happens with velocity.

Tests were done with velocity stable and dev build with only botsentry as a plugin

Here the message.
![2](https://user-images.githubusercontent.com/85011614/169791450-ca1cff48-aa21-49bf-ae69-30545d92f855.png)
.

**Comment by Laurenshup** [comment]
I cannot reproduce this error with the latest dev build of Velocity. Can you try testing it again?

**Comment by SkyDude0** [comment]
for now i cant, i remove velocity
