### ISSUE TITLE
can't remove forced whitelist ip

### ISSUE THREAD

**Issue by OPNetworkLOL** [BlackDemonZyT/BotSentry#86]
i can clear all forced whitelist ip, but i can't remove single forced whitelist ip
![unknown](https://user-images.githubusercontent.com/87759199/171746669-17613974-4d6f-42d7-a0cf-6efbf3d8525a.png)

**Comment by Laurenshup** [comment]
Maybe this problem has something to do with #71.

**Comment by Laurenshup** [comment]
This issue has been identified in the code and fixed. This will be included in the next version.
