### ISSUE TITLE
[Suggestion] Blacklist Reason

### ISSUE THREAD

**Issue by Hutch79** [BlackDemonZyT/BotSentry#90]
Hey, I would suggest adding a Blacklist Reason to the `/bs scan` command. 
Currently, I have no possibility (maybe I haven't found it jet) to check, why a player has been blacklisted.

**Comment by Laurenshup** [comment]
We currently do not save that data, as it will greatly increase the data and processing usage. Do you really think this is needed?

**Comment by Hutch79** [comment]
Uff, this question is old.
Honestly, I have no clue.

Currently, the Plugin runs as second defense line behind TCP-Shield, and most of the time I don't even think about it because it rarely detects something.

From my point of view, this can be closed, since I don't really remember why I wanted this.
