### ISSUE TITLE
[Suggestion] Dolly Whitelist

### ISSUE THREAD

**Issue by Hutch79** [BlackDemonZyT/BotSentry#91]
A dolly whitelist to allow Families or test accounts joining from the same IP.

`/bs whitelist usernames add <username>` does not allow this

![grafik](https://user-images.githubusercontent.com/42042811/180855794-ee63d2d6-8e47-40ed-9e34-d008a0b90784.png)

I would suggest making a whitelist with the Username/UUID and not the IP.

**Comment by Laurenshup** [comment]
This will be in the next version, it is now completely coded. Players who are in the usernames whitelist, won't be kicked by the system anymore.
