### ISSUE TITLE
Have a seperate message for when servers can not be reached 

### ISSUE THREAD

**Issue by TomLewis** [BlackDemonZyT/BotSentry#94]
If you run botsentry on a proxy and have a seperate host for your minecraft servers, if those server(s) go down, but the proxy stays up, Bot sentry tells people their connection is suspicious.

There needs to be a seperate check/message for when servers go down, so that players & staff know whats happeing.

**Comment by Laurenshup** [comment]
Hmm, is this really the case? Can you maybe share a console log for this?
Probably disabling detection.amazon.enabled fixes this.

**Comment by Laurenshup** [comment]
Due to no response, I have to close this.

**Comment by TomLewis** [comment]
This is still an issue.
